var questions = 3;
var questionsLeft = "[" + questions + " questions left!]";
var adjective = prompt( "Type in the adjective " + questionsLeft);
questions -= 1;
var questionsLeft = "[" + questions + " questions left!]";
var verb = prompt( "Type in a verb " + questionsLeft);
questions -= 1;
var questionsLeft = "[" + questions + " questions left!]";
var noun = prompt( "Type in a noun " + questionsLeft);
questions -= 1;
var questionsLeft = "[" + questions + " questions left!]";
alert("All done. Ready for the message? " + questionsLeft);
var solution = "<h2>There once was a ";
solution += adjective;
solution +=  " programmer who wanted to use JavaScript to ";
solution += verb;
solution += " the ";
solution += noun + "</h2>";
document.write(solution);
