var secondsPerMin = 60;
var minsPerHour = 60;
var hoursPerDay = 24;
var daysPerWeek = 7;
var weeksPerYear = 52;
var secondsPerDay = secondsPerMin * minsPerHour * hoursPerDay;
document.write( "<h2>There are " + secondsPerDay + " seconds in a day</h2>");
var yearsAlive = 25;
var secondsAlive = secondsPerDay * daysPerWeek * weeksPerYear * yearsAlive;
document.write("<h2>I have been alive for more than " + secondsAlive + " seconds.</h2>");
